#!/usr/bin/env python3
"""Generate figures/fig-tour-map.tex from the deployed annotations and tour file.

Replaces the photograph of the vendor application screen with a clean vector
export: the annotated points at their recorded coordinates, and the guided-tour
route drawn over them in visiting order. This is what makes the leg count in
Section VI-C legible rather than asserted.

Stops carry their tour index rather than their name. Nine names would not fit
without overlapping the route, and the order is the information that matters
here; the names are listed once in the caption.

    python tools/gen_map_figure.py

Reads   ../../data/points.json      annotation names and coordinates
        ../../data/lab_tour.json    tour order and return point
Writes  figures/fig-tour-map.tex
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent.parent
DATA = ROOT / "data"
OUT = Path(__file__).resolve().parent.parent / "figures" / "fig-tour-map.tex"

# Where each index label sits relative to its marker, tuned so that no label
# crosses the route. Keyed by tour index; "R" is the return point.
ANCHORS = {
    1: "below right", 2: "right", 3: "above", 4: "left", 5: "above left",
    6: "left", 7: "below", 8: "below left", 9: "above right", "R": "right",
}


def tex_escape(text: str) -> str:
    return text.replace("&", r"\&").replace("_", r"\_").replace("%", r"\%")


def main() -> None:
    points = {p["name"]: p for p in json.loads(
        (DATA / "points.json").read_text(encoding="utf-8"))["points"]}
    tour = json.loads((DATA / "lab_tour.json").read_text(encoding="utf-8"))

    stops = [s["target_point"] for s in tour["stops"] if s.get("enabled", True)]
    resolved = [s for s in stops if s in points]
    skipped = [s for s in stops if s not in points]
    ret = tour["return_point"]
    route = resolved + [ret]
    legs = len(route)  # one leg to each stop, plus the return leg

    labelled = list(zip(range(1, len(resolved) + 1), resolved)) + [("R", ret)]
    off_route = sorted(n for n in points if n not in route)

    legend = "; ".join(f"{i}~{tex_escape(n)}" for i, n in labelled)

    lines = [
        "% Fig. 5 - guided-tour route over the deployed annotations.",
        "% GENERATED by tools/gen_map_figure.py - do not edit by hand.",
        "% Regenerate after any change to data/points.json or data/lab_tour.json.",
        f"% {len(points)} annotations, {len(resolved)} resolvable stops"
        + (f" ({', '.join(skipped)} unresolved)" if skipped else "")
        + f", {legs} legs per tour.",
        "\\begin{figure}[!t]",
        "\\centering",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  width=\\columnwidth, height=5.4cm,",
        "  xlabel={$x$ (m)}, ylabel={$y$ (m)},",
        "  label style={font=\\scriptsize}, tick label style={font=\\scriptsize},",
        "  grid=major, grid style={gray!20},",
        "  enlarge x limits=0.10, enlarge y limits=0.14,",
        "  clip=false,",
        "]",
    ]

    coords = " ".join(f"({points[n]['x']:.2f},{points[n]['y']:.2f})" for n in route)
    lines.append(
        "\\addplot[draw=blue!55, thick, -{Stealth[length=4pt]}, mark=none] "
        "coordinates {" + coords + "};"
    )

    if off_route:
        pts = " ".join(f"({points[n]['x']:.2f},{points[n]['y']:.2f})" for n in off_route)
        lines.append(
            "\\addplot[only marks, mark=o, mark size=1.6pt, draw=gray] "
            "coordinates {" + pts + "};"
        )

    for idx, name in labelled:
        p = points[name]
        fill = "green!45!black" if idx == "R" else "blue!45"
        anchor = ANCHORS.get(idx, "above")
        lines.append(
            f"\\addplot[only marks, mark=*, mark size=1.9pt, draw=blue!60!black, "
            f"fill={fill}] coordinates {{({p['x']:.2f},{p['y']:.2f})}} "
            f"node[{anchor}, font=\\tiny, inner sep=1.5pt] {{{idx}}};"
        )

    lines += [
        "\\end{axis}",
        "\\end{tikzpicture}",
        f"\\caption{{Guided-tour route over the annotations deployed through the vendor "
        f"application, in visiting order: {len(resolved)} resolvable stops and a return leg "
        f"(R), {legs} navigation legs per tour. Hollow markers are annotations that exist on "
        f"the map but are not on the tour. Stops: {legend}. Coordinates are the values the "
        f"marker manager reports; reusing the annotations avoids the drift that affects "
        f"coordinates extracted offline, but does not by itself make navigation succeed "
        f"(Section~\\ref{{sec:eval}}-C).}}",
        "\\label{fig:vendormap}",
        "\\end{figure}",
        "",
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"figures/{OUT.name}: {len(points)} annotations, {len(resolved)} stops, {legs} legs")
    if skipped:
        print(f"  unresolved stops skipped: {', '.join(skipped)}")


if __name__ == "__main__":
    main()
