from sdk.models import ReceptionAction

# Le matching vocal (VOICE_COMMAND_MAP, match_voice_command, _normalize_text,
# match_point_navigation, _NAV_PATTERN, _ARTICLE_PREFIX) vit désormais dans
# sdk.voice_commands (module sans pydantic, réutilisable par le backend Termux).
# Ré-exporté ici pour ne rien casser des imports existants.
from sdk.voice_commands import (  # noqa: F401  (ré-exports rétrocompat)
    VOICE_COMMAND_MAP,
    _ARTICLE_PREFIX,
    _NAV_PATTERN,
    _normalize_text,
    match_point_navigation,
    match_voice_command,
    normalize_text,
)

DEFAULT_ACTIONS: list[ReceptionAction] = [
    ReceptionAction(
        id="welcome_guest",
        label="Accueillir un visiteur",
        description="Annonce de bienvenue puis déplacement vers le point d'accueil",
        icon="hand-wave",
        category="accueil",
        speech="Bienvenue ! Je suis votre robot d'accueil. Suivez-moi.",
        target_point="Accueil",
        label_en="Welcome a visitor",
        description_en="Welcome announcement, then move to the reception point",
        speech_en="Welcome! I am your reception robot. Follow me.",
    ),
    ReceptionAction(
        id="go_reception",
        label="Aller à l'accueil",
        description="Navigation autonome vers le poste d'accueil",
        icon="map-pin",
        category="navigation",
        target_point="Accueil",
        label_en="Go to reception",
        description_en="Autonomous navigation to the reception desk",
    ),
    ReceptionAction(
        id="go_meeting_room",
        label="Conduire en salle",
        description="Accompagner le visiteur vers la salle de réunion",
        icon="navigation",
        category="navigation",
        speech="Je vous accompagne en salle. Suivez-moi s'il vous plaît.",
        target_point="Salle A",
        label_en="Lead to meeting room",
        description_en="Accompany the visitor to the meeting room",
        speech_en="I will take you to the meeting room. Please follow me.",
    ),
    ReceptionAction(
        id="wait_mode",
        label="Mode attente",
        description="Se placer au point d'attente et rester disponible",
        icon="clock",
        category="accueil",
        speech="Je reste à votre disposition.",
        target_point="Attente",
        label_en="Standby mode",
        description_en="Move to the waiting point and stay available",
        speech_en="I remain available for you.",
    ),
    ReceptionAction(
        id="return_charge",
        label="Retour à la pile",
        description="Renvoyer le robot vers la station de charge",
        icon="plug",
        category="maintenance",
        target_point="Pile",
    ),
    ReceptionAction(
        id="guided_tour",
        label="Visite guidée",
        description="Lancer un parcours de visite prédéfini (GUIDED)",
        icon="route",
        category="accueil",
        speech="Bienvenue pour la visite guidée. Nous allons commencer.",
        route_name="visite_standard",
        label_en="Guided tour",
        description_en="Start a predefined visit route (GUIDED)",
        speech_en="Welcome to the guided tour. Let's get started.",
    ),
    ReceptionAction(
        id="inform_waiting",
        label="Informer d'un délai",
        description="Annoncer un temps d'attente estimé",
        icon="message",
        category="accueil",
        speech="Votre interlocuteur arrive dans quelques instants. Merci de patienter.",
        label_en="Announce a delay",
        description_en="Announce an estimated waiting time",
        speech_en="Your contact will arrive shortly. Thank you for waiting.",
    ),
    ReceptionAction(
        id="stop_all",
        label="Arrêter l'action",
        description="Interrompre navigation et annonces en cours",
        icon="stop",
        category="sécurité",
        label_en="Stop",
        description_en="Interrupt current navigation and announcements",
    ),
]
